services:
  booking_app_db:
    container_name: booking_app_db
    image: mysql
    restart: unless-stopped
    env_file:
      - ./.env
    ports:
      - $MYSQL_LOCAL_PORT:$MYSQL_DOCKER_PORT
    environment:
      - MYSQL_DATABASE=$MYSQL_DB
      - MYSQL_ROOT_PASSWORD=$MYSQL_ROOT_PASSWORD

  booking-service:
    container_name: booking_app
    depends_on:
      - booking_app_db
    restart: on-failure
    image: booking-service
    build: .
    env_file: ./.env
    ports:
      - $SPRING_LOCAL_PORT:$SPRING_DOCKER_PORT
      - $DEBUG_PORT:$DEBUG_PORT
    environment:
      SPRING_APPLICATION_JSON: '{
            "spring.datasource.url" : "jdbc:mysql://database:$MYSQL_DOCKER_PORT/$MYSQL_DB?createDatabaseIfNotExist=true",
            "spring.datasource.username" : "$MYSQLDB_USER",
            "spring.datasource.password" : "$MYSQL_ROOT_PASSWORD"
            }'
      JAVA_TOOL_OPTIONS: "-agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:5005"
